### PR TITLE
ci: use actions-gh-pages to deploy a rust template sample

### PR DESCRIPTION
**Pull request by pplmx**

### CODE REVIEW

**Comment by marcoieni** [comment]
Hi Mystic!
Thanks for contributing to the project! 

The example at the moment is deployed [here](https://github.com/rust-github/rust-gh-example). 

Why have you done this change?
What's the advantage of having the repository deployed in github pages?
Isn't better to deploy it to an actual github repo like we do at the moment?

**Comment by pplmx** [comment]
Only use this action to simplify the code, its behavior is the same to your previous logic.

**Comment by marcoieni** [comment]
Have you tested it by trying to fork the project? For sure the actual CI is convoluted, but it preserves some [files](https://github.com/rust-github/template/blob/a8ff862719be78fa965cd18d1ae8ab8f327f9db3/.github/workflows/cd.yaml#L38-L40) which are different from the generated ones.

**Comment by pplmx** [comment]
Yep, I have tried it. Here is my test case [template](https://github.com/x-pt/template) and [example](https://github.com/x-pt/example)

For my solution, every file will be regenerated.

**Comment by marcoieni** [comment]
I see, unfortunately those files should be preserved.
For example, the [Cargo.toml](https://github.com/rust-github/rust-gh-example/blob/main/Cargo.toml) contains the version (0.1.7) of rust-gh-example, which is important because we publish it to crates.io.

**Comment by pplmx** [comment]
Oh, your example is not only an auto-generated project, and also a rust github project example for the newbies. I see. :)

**Comment by marcoieni** [comment]
Yes, by the way, thank you for contributing to this project! :)

**Pull request closed without merging**
